### ISSUE TITLE
New wikisource locations

### ISSUE THREAD

**Issue by funderburkjim** [sanskrit-lexicon/ApteES#2]
1. The pdf to use for  Apte English Sanskrit dictionary on wikisource is
   https://en.wikisource.org/wiki/Index:Ae_test1.pdf.
   This pdf has all 501 pages of the body of the dictionary.
   A pdf with the first five pages was formerly at:
   https://en.wikisource.org/wiki/Index:Apte_English-Sanskrit_Dictionary_Test.pdf
2. The individual digitization pages can be arrived at by clicking the pages in the Index from the Ae_test1.pdf page mentioned above.  
3. The first 10 pages of the digitization have been uploaded.
4.  The first 5 pages in the new version contain all the changes Shalu has made.
5.  New changes should be made on the Ae_test1.pdf version.  The prior test version should no longer be used.

**Comment by drdhaval2785** [comment]
Now the work is not done in wikisource. Can we close this @funderburkjim ?

**Comment by funderburkjim** [comment]
Agree with close of issue.

**Comment by gasyoun** [comment]
> Now the work is not done in wikisource.

@funderburkjim no need in wikisource or just no need lately?

**Comment by funderburkjim** [comment]
Work not done in wikisource.  It was too complicated to be useful.
