### ISSUE TITLE
Corrections of 'missing data' 

### ISSUE THREAD

**Issue by funderburkjim** [sanskrit-lexicon/ApteES#4]
Sampada (mostly) and I have resolved the 450+ instances of missing data in the ae.txt.

The changes are in the 'missingByLine.txt' file in the aexml download.

Prompted by your recent comments regarding the need for better documentation of corrections,  I think that a note of this batch of corrections should be made somewhere;  but I'm not sure where exactly.

Any suggestions?

I need to do something similar for the corrections of missing VCP data that Sampada did, and for the AE corrections (via wikisource) that Shalu has done.

**Comment by drdhaval2785** [comment]
Now the history is well tracked, unlike in earlier times. Closing.
