### ISSUE TITLE
Headword corrections 

### ISSUE THREAD

**Issue by funderburkjim** [sanskrit-lexicon/ApteES#5]
About 75 of the English headwords in ApteES were corrected. See https://github.com/sanskrit-lexicon/ApteES/tree/master/hwspellcheck/readme.org for more details.

Here's a summary.

Using the xspell dictionaries en_GB.dic and en_US.dic and the pyenchant interface to such dictionaries,
all the headwords in aehw2.txt  were checked.  1562 headwords were not found in this way.

After noticing that some of these (like abbacy) WERE found via a Google search such as define:abbacy,  a search was made for an API to this Google search.  However, Google apparently discontinued its dictionary API two or three years ago.  But, Google Docs DOES have a spellcheck feature, which seems to use the same dictionary as 'define:' searches.

So, the list of 1562 headwords was loaded into a google Doc.  Misspelled words are indicated in Google Docs by a red-underlining of misspelled words.  So, It was not too tedious to simply add markup to the ones which Google Docs identified as misspelled.  There were 281 of these.

The next step was to check the scans for AE for these 281 candidates, and mark those that were actually misspelled in the digitization.

77 remained; and corrections to them have been made.

It seems promising that a similar approach can be helpful for finding corrections elsewhere.  The first thing that comes to mind is to try this approach for headwords in the other two English-Sanskrit Dictionaries.

Assuming we can get Google  Docs to do German spellchecks, this approach might be useful for checking the textual German words in the Sanskrit-German dictionaries.

Incidentally, this work made me realize that ApteES has a large number of very obscure English words; and probably has odd (though not wrong) spellings of several headwords.

**Comment by drdhaval2785** [comment]
Seems a job done. Closing.
