### ISSUE TITLE
Ngram approach to finding errors in Sanskrit words of AE

### ISSUE THREAD

**Issue by funderburkjim** [sanskrit-lexicon/ApteES#6]
This summarizes the approach used for finding candidates for spelling errors in the Sanskrit words appearing in the body of the entries.

See the [ae_saninvert readme](https://github.com/sanskrit-lexicon/ApteES/tree/master/ae_saninvert) for the exact details of programmatic steps.

**Comment by gasyoun** [comment]
> This summarizes

Really short one.

**Comment by funderburkjim** [comment]
## inverted index

First step is to create an inverted index of the sanskrit words.  The result is invert2.txt.

The Sanskrit words are clearly marked in the body of the digitization as such, since they appear in Devanagari within the dictionary.  The xml version of the digitization (ae.xml) is used for this purpose.

For each Sanskrit word, the invert2.txt file shows:
* the word, in the SLP1 spelling
* the count of headwords in which the word appears  (recall, the headwords here are English words)
* then a list of the headwords in which the Sanskrit word appears:
  * the (English) headword
  * the sequence number (L-code) of the headword
  * the page number of the scanned image where the headword appears.

There are 61,495 such records in invert2.txt.

**Comment by funderburkjim** [comment]
## words crossing line boundaries.

The digitization (ae.txt) has the nice feature that each line corresponds to a line of the printed text.  

Quite often, a sanskrit word will be hyphenated due to crossing a line boundary.  Also, hyphenation often occurs for words not crossing a line boundary.

The words crossing a line boundary present special problems in the identification of spelling problems.
The current version makes an expedient choice of handling these cases, treating them as if there were no line crossing, but retaining the hyphenation at the end of the line.

It would be possible to examine these line-spanning words separately, but we have not yet done so.

**Comment by gasyoun** [comment]
> The words crossing a line boundary present special problems in the identification of spelling problems.

How many?

**Comment by funderburkjim** [comment]
## identify words as headwords 

The next step separates the list of Sanskrit words into two categories, depending on whether the
word appears as a headword in one of the other Sanskrit dictionaries at Cologne.

The source of Sanskrit headwords is taken as [hwnorm1c.txt](https://github.com/sanskrit-lexicon/hwnorm1/blob/master/ejf/hwnorm1c/hwnorm1c.txt).  There are about 385,000 Sanskrit headwords in this list.

> Note that hwnorm1c.txt has been copied into this repository.

This filtering is done in several steps:
* first, search for matches with removal of all hyphens
* For those not found, search for match when all word parts (due to hyphenation) are found
* For those not found, remove hyphens and try to partition each remaining word W into any
   two parts XY, and try to find both X and Y in hwnorm1.

The remaining unfound list is in invert2_notfound3.txt, which has 16797 items.
These words will be subjected to further analysis as described below.

**NOTE** The matching with hwnorm1 mentioned above takes into account the spelling normalization of hwnorm1.  This normalization includes such things as uniform nasalization, removal of ending visarga and anusvara, and several other lesser spelling variations.  The `normalize_key` function in [hwnorm1.py](https://github.com/sanskrit-lexicon/ApteES/blob/master/ae_saninvert/hwnorm1/hwnorm1.py) shows all the details of normalization.

**Comment by funderburkjim** [comment]
@gasyoun  line-crossing words not currently examined. Don't know how many there are.

**Comment by funderburkjim** [comment]
## hwnorm1 ngrams

In preparation for further filtering,  lists of ngrams are computed fromthe list of hwnorm1 Sanskrit words.

Currently this has been done for 2-grams (pairs of letters) and 3-grams (triplets of letters). These lists
are in ae_saninvert/hwnorm1 directory as files 2gram.txt and 3gram.txt.

**Comment by funderburkjim** [comment]
## filter not-found list for odd n-grams

In this last step, the filter_ngram.py prgram filters the list of not-found words (invert2_notfound3.txt for
letter sequences not found (again, after hwnorm1 normalization of spelling) in the hwnorm1 ngrams.

The results for 2-grams are in file [invert2_notfound3_ngram2prob.txt](https://github.com/sanskrit-lexicon/ApteES/blob/master/ae_saninvert/invert2_notfound3_ngram2prob.txt), which has  155 cases.

**Comment by funderburkjim** [comment]
This list of 155 cases is currently under examination, with the help of Sampada.  A form 
[http://www.sanskrit-lexicon.uni-koeln.de/scans/AEScan/2014/pywork/correctionwork/issue-306-demo/update.php] has been developed to facilitate this examination.

After about half the cases, we have found that almost all the cases are indeed errors in spelling,
so the *precision* of the filter selection appears to be high.

When these cases have been examined , cases involving 3-grams will be generated.  And we'll probably
continue looking at longer n-grams as long as the precision remains acceptably high.

**Comment by drdhaval2785** [comment]
https://github.com/sanskrit-lexicon/CORRECTIONS/blob/master/dhaval/descriptionerrors/aevsvcperrors.txt
may be of interest to you.
Not normalised. And base ngrams are VCP whole text.

**Comment by gasyoun** [comment]
> almost all the cases are indeed errors in spelling

Well done.

**Comment by funderburkjim** [comment]
@drdhaval2785   Thanks for the link above of likely AE errors.  List looks promising.

**Comment by Andhrabharati** [comment]
@funderburkjim / @drdhaval2785 ,

I have a proposal, which you might be interested in.

**Comment by Andhrabharati** [comment]
We, at AB, did some basic/quick corrections in the Apte E2S, for our hosting few years back.

Now I am thinking of doing a full proofing of the work, esp. as we are in possession of an excellent print, clear text throughout.

Would you also like to have it, for your hosting?

This being the smallest work, starting with this now; before taking up AP1919 (not AP1890) S2E, which is my 2nd one in line next.

If I get a positive here, I will elaborate what I want from you.

Else, I will just continue with our file itself, for our use.

Planning to start the work this Saturday, so you've two days to respond on this.

**Comment by drdhaval2785** [comment]
Obviously we would be interested in incorporating your work. We would not at all love to reinvent the wheel.

**Comment by Andhrabharati** [comment]
> Obviously we would be interested in incorporating your work. We would not at all love to reinvent the wheel.

Good to hear from you @drdhaval2785.

I will wait to hear from @funderburkjim as well, as he is the decision maker, and also has to work a little bit on this for me.

**Comment by funderburkjim** [comment]
What do you need?

**Comment by Andhrabharati** [comment]
@funderburkjim, 

Let me start with an example entry **Continue** (in print).

This is how Cologne has it-

![image](https://user-images.githubusercontent.com/75209130/129938901-07dc89e0-35d2-4b73-b40f-4ba25eeeba4d.png)

Now look at how we have it at AB, with splitting of sub-entries as new entries (and appropriate body splits)-

![image](https://user-images.githubusercontent.com/75209130/129939052-41a7041a-a65c-49eb-8c5e-36c978d01980.png)

![image](https://user-images.githubusercontent.com/75209130/129939168-082415f2-d60a-4a58-92b1-57b47c206c6f.png)

![image](https://user-images.githubusercontent.com/75209130/129939296-878ea5ba-6fc9-4491-bfe3-27dc2fd3fbcf.png)

![image](https://user-images.githubusercontent.com/75209130/129939391-7552dbb5-4693-4a8e-b873-060166213f02.png)

**Sub-entry expansion as new full entries:**
It may be seen that wherever applicable the sub-entries retain the "group info" (CSV format at HW level), and the parent/child relation is indicated throughout(using >> and << marks); this is the de facto style we adopted across all our dictionaries content, both Telugu section and Sanskrit section.

At Cologne, only the MW99 has this splitting done for the sub-entries; and groups is now almost completely done (after my entering the group).

I guess this sub-entry splitting should be done across all the dictionaries [and expanded as full word(s), if in reduced form].

If agreed upon this point, I can extend my support in doing this piece of work for all Cologne dictionaries.

Similarly, there are multiple points that could (and should) be done, but I do not want to list them all here.
`------------------------`

Now coming to the point of 
> What do you need?

Just need your opinion on using my file as is [you've already seen my AP90 file; as a sample with splitting/grouping etc. & no retention of line breaks], or if you want to have it with meta-lines & line breaks (and no "clear body splits" at POS and meanings) as you have presently, need a simple "Devanagari converted" file of your data. [No SLP1 at all.]

**What do you say now?**
[BTW, I didn't expect you would be responding so fast, @funderburkjim !!]

**Comment by funderburkjim** [comment]
Is it correct that the Andhrabharati web site display of ApteES is based on the Cologne data 'apte.txt'.  ?

**Comment by funderburkjim** [comment]
In preparation for a Devanagari version of ae.txt, removed periods from Devanagari text.
See [This commit of ae.txt](https://github.com/sanskrit-lexicon/csl-orig/commit/f2734fb8ac5ae662cc9fa62c6053a80078df8677).

**Comment by funderburkjim** [comment]
## which form preferred:

There is potential utility to Cologne efforts in both forms you mention.

## current Cologne form
If you make only corrections here, they will be easily identified and incorporated into Cologne digitization. So ease of
use is the advantage to this form.

## Andhrabharati form 'as is'
Assuming this form is the basis of the andhrabharati.com web site display, this form provides considerable additional information, such as
* resolution of line-breaks
* resolution of abbreviated sub-headwords 
* markup of grammatical subsections.
* etc.

However, the added information of the 'as is' form will be harder to integrate into Cologne site due to the significant differences in format.

If you can prepare both forms, that would be the best.  But if you only present one form, then choose the 'as is' Andhrabharati form, since the 'as is' form contains more additional information.

**Comment by Andhrabharati** [comment]
@funderburkjim,

you are late by a day! I've already started my work in our style on our (Indian) Saturday afternoon, about 10 hrs ago.

And I am estimating a time-frame of 4-6 weeks for its completion.

**Comment by gasyoun** [comment]
> I guess this sub-entry splitting should be done across all the dictionaries [and expanded as full word(s), if in reduced form].

Agree, but how much time would it take to? Let's speak about the major dictionaries first.

**Comment by Andhrabharati** [comment]
> > I guess this sub-entry splitting should be done across all the dictionaries [and expanded as full word(s), if in reduced form].
> 
> Agree, but how much time would it take to? Let's speak about the major dictionaries first.
> 

@drdhaval2785 and @funderburkjim do not like points unrelated to the issue heading to be discussed!!

no use of my proposals, unless they agree (them being the maintenance team).

> > If agreed upon this point, I can extend my support in doing this piece of work for all Cologne dictionaries.
> 
> I agree and we have spoken about it in the past, but it seems a work bigger than we can handle.
> 

@drdhaval2785 and @funderburkjim do not like points unrelated to the issue heading to be discussed!!

no use of my proposals, unless they agree (them being the maintenance team).


> > estimating a time-frame of 4-6 weeks for its completion
> 
> For Apte only, right?

yes, of course.

**Comment by funderburkjim** [comment]
Can this issue be closed now?

**Comment by Andhrabharati** [comment]
yes.
