### ISSUE TITLE
Can anusvAra precede vowel

### ISSUE THREAD

**Issue by funderburkjim** [sanskrit-lexicon/ApteES#7]
We encountered the spelling `saMfD`  within the entry 'thrive' in this dictionary.

![image](https://cloud.githubusercontent.com/assets/6393033/20849771/327941e4-b8a6-11e6-8e5a-657a9c5453d6.png)

While we know that Apte loves anusvAra in place of homorganic nasals,
it seems likely that using anusvAra before a vowel, as shown here, is in fact an error.

Is there some grammar rule which prohibits anusvAra before vowel?

(if so, this instance in AE will be classified as a print error).

**Comment by gasyoun** [comment]
> Is there some grammar rule which prohibits anusvAra before vowel?

Let @drdhaval2785 say.

> Apte loves anusvAra in place of homorganic consonants

As all Indian books love...

**Comment by drdhaval2785** [comment]
Not possible grammtically to have M[vowel] combination.
 http://sanskritdocuments.org/learning_tools/sarvanisutrani/8.3.23.htm

This rule changes m to M before only consonants.

**Comment by funderburkjim** [comment]
Thanks, Dhaval, for putting the decision on firm ground.

  Sampada's intuition on this was right.
